name: DevSecOps Workflow

on: push

env:
  IMAGE_TAG: ghcr.io/${{ github.repository }}:unstable

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Gitleaks Scan
        run: |
          docker run --rm -v $(pwd):/code zricethezav/gitleaks:v8.18.1 -s /code detect
  
  
  depscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run OWASP Dep-Scan
        uses: docker://ghcr.io/owasp-dep-scan/dep-scan:v5.2.2
        with:
          args: --src /github/workspace

  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Semgrep
        uses: docker://returntocorp/semgrep
        with:
          args: semgrep scan /github/workspace

  build:
    runs-on: ubuntu-latest
    outputs:
      image_path: ${{ steps.build_output.outputs.image_path }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image with Kaniko
        id: build_image
        uses: docker://gcr.io/kaniko-project/executor:v1.9.2
        with:
          args: --destination=${{ env.IMAGE_TAG }} --context=/github/workspace --dockerfile=/github/workspace/Dockerfile --no-push --tarPath /github/workspace/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  trivy_scan:
    needs: build
    runs-on: ubuntu-latest
    container: aquasec/trivy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .
      - name: Scan the Docker image with Trivy
        run: trivy image --exit-code 1 --severity CRITICAL --ignore-unfixed --no-progress --input image.tar

  push:
    needs: [build, trivy_scan, gitleaks, depscan, semgrep]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .
      - name: Login and push
        run: docker run --entrypoint "" gcr.io/go-containerregistry/crane crane auth login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io && crane push /gitlab/workspace/image.tar ${{ env.IMAGE_TAG }}
