name: DevSecOps Workflow

on: push

env:
  IMAGE_TAG: ghcr.io/${{ github.repository }}:unstable

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Gitleaks Scan
        run: |
          docker run --rm -v $(pwd):/code zricethezav/gitleaks:v8.18.1 -s /code detect -f sarif -r /code/gitleaks.sarif.json  
      - name: Upload sarif file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif.json
          category: gitleaks
  
  depscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run OWASP Dep-Scan
        uses: docker://ghcr.io/owasp-dep-scan/dep-scan:v5.2.2
        with:
          args: --src /github/workspace

  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Semgrep
        uses: docker://returntocorp/semgrep
        with:
          args: semgrep scan /github/workspace

  build:
    runs-on: ubuntu-latest
    outputs:
      image_path: ${{ steps.build_output.outputs.image_path }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image with Kaniko
        id: build_image
        uses: docker://gcr.io/kaniko-project/executor:v1.9.2
        with:
          args: --destination=${{ env.IMAGE_TAG }} --context=/github/workspace --dockerfile=/github/workspace/Dockerfile --no-push --tarPath /github/workspace/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  trivy_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .
      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/image.tar
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
  push:
    needs: [build, trivy_scan, gitleaks, depscan, semgrep]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .
      - uses: imjasonh/setup-crane@v0.1
      - name: Push Docker image to GitHub Container Registry
        run: crane push image.tar ${{ env.IMAGE_TAG }}