name: Gitleaks Scan

on: push

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure Git Exception
        run: git config --global --add safe.directory /github/workspace

      - name: Run Gitleaks Scan
        run: |
          docker run --rm -v $(pwd):/code zricethezav/gitleaks:v8.18.1 --repo-path=/code detect