name: Gitleaks Scan

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the workflow on

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Gitleaks Scan
        uses: docker://zricethezav/gitleaks:v8.18.1
        with:
          args: --verbose