name: SAST
on: push

jobs:
  depscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Semgrep
        uses: docker://returntocorp/semgrep
        with:
          args: semgrep scan /github/workspace